<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            margin: 0;
            padding: 2rem;
          }
          a {
            color: #0051C3;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
            background: #fff;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            border-radius: 8px;
          }
          th {
            background: #f8f9fa;
            padding: 1rem;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid #eee;
          }
          td {
            padding: 1rem;
            border-bottom: 1px solid #eee;
            vertical-align: top;
          }
          tr:last-child td {
            border-bottom: none;
          }
          .url-cell {
            word-break: break-all;
          }
          .meta-cell {
            width: 200px;
            color: #666;
          }
          .image-list {
            list-style: none;
            padding: 0;
            margin: 0.5rem 0 0 0;
            font-size: 0.9rem;
          }
          .image-list li {
            margin: 0.25rem 0;
            padding-left: 1rem;
            position: relative;
          }
          .image-list li:before {
            content: "•";
            position: absolute;
            left: 0;
            color: #999;
          }
          .header {
            margin-bottom: 2rem;
          }
          .header h1 {
            margin: 0 0 0.5rem 0;
            color: #1a1a1a;
          }
          .header p {
            margin: 0;
            color: #666;
          }
          .count {
            background: #f8f9fa;
            padding: 0.5rem 1rem;
            border-radius: 4px;
            margin-bottom: 1rem;
            display: inline-block;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>XML Sitemap</h1>
          <p>Generated by IndexOf.ID</p>
        </div>
        
        <div class="count">
          <xsl:choose>
            <xsl:when test="count(sitemap:urlset/sitemap:url) &gt; 0">
              This sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
            </xsl:when>
            <xsl:otherwise>
              This sitemap contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.
            </xsl:otherwise>
          </xsl:choose>
        </div>

        <xsl:choose>
          <xsl:when test="count(sitemap:urlset/sitemap:url) &gt; 0">
            <table>
              <tr>
                <th>URL</th>
                <th>Images</th>
                <th>Priority</th>
                <th>Last Modified</th>
              </tr>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td class="url-cell">
                    <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                  </td>
                  <td class="meta-cell">
                    <xsl:if test="image:image">
                      <ul class="image-list">
                        <xsl:for-each select="image:image">
                          <li><xsl:value-of select="image:title"/></li>
                        </xsl:for-each>
                      </ul>
                    </xsl:if>
                  </td>
                  <td class="meta-cell">
                    <xsl:if test="sitemap:priority">
                      <xsl:value-of select="sitemap:priority"/>
                    </xsl:if>
                  </td>
                  <td class="meta-cell">
                    <xsl:if test="sitemap:lastmod">
                      <xsl:value-of select="substring(sitemap:lastmod, 0, 11)"/>
                    </xsl:if>
                  </td>
                </tr>
              </xsl:for-each>
            </table>
          </xsl:when>
          <xsl:otherwise>
            <table>
              <tr>
                <th>Sitemap</th>
                <th>Last Modified</th>
              </tr>
              <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                <tr>
                  <td class="url-cell">
                    <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                  </td>
                  <td class="meta-cell">
                    <xsl:if test="sitemap:lastmod">
                      <xsl:value-of select="substring(sitemap:lastmod, 0, 11)"/>
                    </xsl:if>
                  </td>
                </tr>
              </xsl:for-each>
            </table>
          </xsl:otherwise>
        </xsl:choose>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet> 